# A mapping of subject codes to their full subject names.
SUBJECT_NAME_MAP = {
    "AAD": "Architecture, Arts, and Design",
    "AAEC": "Agricultural and Applied Economics",
    "ABA": "Accounting & Business Analysis",
    "ACIS": "Accounting and Information Systems",
    "ADR": "Architecture and Design Research",
    "ADV": "Advertising",
    "AE": "Aerospace Engineering",
    "AEE": "Agricultural and Extension Education",
    "AFST": "Africana Studies",
    "AGIE": "Career and Technical Education – Agricultural Education",
    "AGRB": "Agribusiness",
    "AGSC": "Agricultural Sciences",
    "AHRM": "Apparel, Housing, and Resource Management",
    "AINS": "American Indian Studies",
    "ALCE": "Agriculture, Leadership, and Community Education",
    "ALS": "Agricultural and Life Sciences",
    "ANSD": "Animal Sciences, Dairy",
    "ANSP": "Animal Sciences, Poultry",
    "AOE": "Aerospace and Ocean Engineering",
    "APEL": "Applied Electromagnetics",
    "APS": "Appalachian Studies",
    "APSC": "Animal and Poultry Sciences",
    "ARBC": "Arabic",
    "ARCG": "Architecture",
    "ARCH": "Architecture",
    "ART": "Art",
    "AS": "Military, Aerospace Studies",
    "ASPT": "Social, Political, Ethical, and Cultural Thought",
    "AT": "Agricultural Technology",
    "AUTE": "Automotive Engineering",
    "BAD": "Business Administration",
    "BBIT": "Business, Business Information Technology",
    "BC": "Building Construction",
    "BCHM": "Biochemistry",
    "BCSM": "Building/Construction Science and Management",
    "BDS": "Behavioral Decision Science",
    "BFIN": "Business, Finance",
    "BHTM": "Business, Hospitality and Tourism Management",
    "BIOC": "Biochemistry",
    "BIOL": "Biological Sciences",
    "BIT": "Business Information Technology",
    "BMES": "Biomedical Engineering",
    "BMGT": "Business, Management",
    "BMKT": "Business, Marketing",
    "BMSP": "Biomedical Sciences and Pathobiology",
    "BMVS": "Biomedical and Veterinary Sciences",
    "BSE": "Biological Systems Engineering",
    "BUS": "Business",
    "BXBR": "Business, Executive Business Research",
    "CBNU": "Cognitive and Behavioral Neuroscience",
    "CDI": "Commercial Development and Investment",
    "CE": "Civil Engineering",
    "CED": "Community Economic Development",
    "CEE": "Civil and Environmental Engineering",
    "CEEN": "Civil Engineering",
    "CEM": "Construction Engineering and Management",
    "CESL": "Construction Safety Leadership",
    "CFPF": "Financial Planning and Wealth Management",
    "CHE": "Chemical Engineering",
    "CHEM": "Chemistry",
    "CHN": "Chinese",
    "CINE": "Cinema",
    "CLA": "Classical Studies",
    "CLD": "Community Leadership and Development",
    "CMA": "Cybersecurity Management and Analytics",
    "CMDA": "Computational Modeling and Data Analytics",
    "CMNW": "Communications & Networking",
    "CMST": "Communication Studies",
    "CNEU": "Clinical Neuroscience",
    "CNST": "Construction",
    "COMM": "Communication",
    "CONS": "Consumer Studies",
    "COS": "College of Science",
    "CPE": "Computer Engineering",
    "CPED": "Childhood Pre-Education",
    "CPI": "Chip-Scale Integration",
    "CRA": "Controls, Robotics & Autonomy",
    "CRIM": "Criminology",
    "CS": "Computer Science",
    "CSA": "Computer Science and Applications",
    "CSES": "Crop and Soil Environmental Sciences",
    "CSNU": "Computational and Systems Neuroscience",
    "CSS": "Crop and Soil Environmental Sciences",
    "CSSC": "Crop and Soil Sciences",
    "CTCH": "Creative Technologies",
    "CTEC": "Creative Technologies",
    "CTED": "Career and Technical Education",
    "CW": "Creative Writing",
    "DAAS": "Data Analysis and Applied Statistics",
    "DANC": "Dance",
    "DASC": "Dairy Science",
    "DCC": "Data-Centric Computing",
    "EAHS": "Exercise and Health Sciences",
    "ECAS": "Economics",
    "ECE": "Electrical and Computer Engineering",
    "ECDE": "Early Childhood Development and Education",
    "ECOE": "Ecological Engineering",
    "ECON": "Economics",
    "ECRA": "Controls, Robotics & Autonomy",
    "ECS": "Environmental Conservation & Society",
    "ECSG": "Economics, Science",
    "EDAC": "Adult and Continuing Education",
    "EDAD": "Educational Administration",
    "EDCH": "Community Health Education",
    "EDCI": "Curriculum and Instruction",
    "EDCO": "Counselor Education",
    "EDCT": "Career and Technical Education",
    "EDEL": "Educational Leadership",
    "EDEP": "Educational Psychology",
    "EDGE": "Environment, Development, and Global Economy",
    "EDHE": "Higher Education",
    "EDIT": "Instructional Design and Technology",
    "EDP": "Environmental Design and Planning",
    "EDPE": "Health and Physical Education",
    "EDRE": "Educational Research and Evaluation",
    "EDS": "Environmental Data Science",
    "EDSP": "Student Personnel Services",
    "EDTE": "Technology Education",
    "EE": "Electrical Engineering",
    "EEMG": "Event & Experience Management",
    "EEMP": "Environmental Economics: Management and Policy",
    "EENG": "Environmental Engineering",
    "EIT": "Entrepreneurship, Innovation & Technology Management",
    "ELAE": "English Language Arts Education",
    "ELE": "Elementary Education (PK-6)",
    "ELPS": "Educational Leadership and Policy Studies",
    "EM": "Engineering Mechanics",
    "ENCW": "Creative Writing",
    "ENE": "Environmental Engineering",
    "ENGE": "Engineering Education",
    "ENGL": "English",
    "ENGR": "Engineering",
    "ENSC": "Environmental Science",
    "ENT": "Entomology",
    "EPP": "Environmental Policy and Planning",
    "ER": "Ecological Restoration",
    "ERES": "Energy & Power Electronics Systems",
    "ERM": "Environmental Resources Management",
    "ESEN": "Environmental Sciences and Engineering",
    "ESM": "Engineering Science and Mechanics",
    "ETE": "Engineering Technology, Electrical",
    "EUTS": "European and Transatlantic Studies",
    "EVHT": "Environmental Horticulture",
    "EXPN": "Experimental Neuroscience",
    "FA": "Fine Arts",
    "FBDA": "FinTech and Big Data Analytics",
    "FHSE": "Food and Health Systems Economics",
    "FIN": "Finance",
    "FISC": "Fish Conservation",
    "FIW": "Fisheries and Wildlife",
    "FL": "Foreign Language",
    "FLCL": "Foreign Languages, Cultures, and Literatures",
    "FMD": "Fashion Merchandising and Design",
    "FOR": "Forestry",
    "FORS": "Forestry",
    "FPR": "Forest Products",
    "FR": "French",
    "FREC": "Forest Resources and Environmental Conservation",
    "FREL": "Finance and Real Estate",
    "FST": "Food Science and Technology",
    "GAEA": "Geospatial and Environmental Analysis",
    "GBCB": "Genetics, Bioinformatics, and Computational Biology",
    "GBUA": "Business, Accounting and Information Systems",
    "GEOG": "Geography",
    "GEOP": "Geophysics",
    "GEOS": "Geosciences",
    "GER": "German",
    "GIA": "Global & International Affairs",
    "GR": "Greek",
    "GRAD": "Graduate Studies",
    "GRAP": "Graphic Design",
    "HD": "Human Development",
    "HED": "Higher Education and Student Affairs",
    "HGED": "Higher Education",
    "HIST": "History",
    "HNFE": "Human Nutrition, Foods and Exercise",
    "HORT": "Horticulture",
    "HPS": "Humanities for Public Service",
    "HSSE": "History and Social Sciences Education",
    "HTM": "Hospitality and Tourism Management",
    "HUM": "Humanities",
    "IAE": "Information Security Assurance",
    "IAT": "Integrated Agriculture Technologies",
    "IDS": "Industrial Design",
    "IPHD": "Individual Interdisciplinary PhD",
    "IPPL": "International Public Policy",
    "IREL": "International Relations",
    "IS": "International Studies",
    "ISC": "Integrated Science",
    "ISE": "Industrial and Systems Engineering",
    "IT": "Information Technology",
    "ITAL": "Italian",
    "ITD": "International Trade and Development",
    "ITDS": "Interior Design",
    "JMC": "Journalism and Mass Communication",
    "JPN": "Japanese",
    "JUD": "Judaic Studies",
    "LAR": "Landscape Architecture",
    "LAT": "Latin",
    "LAHS": "Liberal Arts and Human Science",
    "LDRS": "Leadership Studies",
    "LSAE": "Agricultural and Extension Education",
    "LTS": "Landscape Design and Turfgrass Science",
    "MACR": "Macromolecular Science and Engineering",
    "MATH": "Mathematics",
    "MCA": "Management Consulting and Analytics",
    "MCHL": "Machine Learning",
    "MCP": "Material Culture and Public Humanities",
    "MDCH": "Medicinal Chemistry",
    "ME": "Mechanical Engineering",
    "MECE": "Materials Engineering Science, Chemical Engineering",
    "MECH": "Materials Engineering Science, Chemistry",
    "MECS": "Materials Engineering Science, Computer Science",
    "MEEE": "Materials Engineering Science, Electrical Engieering",
    "MEFP": "Materials Engineering Science, Forest Products",
    "MEFR": "Materials Engineering Science, Forestry",
    "MEGS": "Materials Engineering Sciences, Geological Sciences",
    "MEME": "Materials Engineering Science, Mechanical Engineering",
    "MEMI": "Materials Engineering Science, Mining Engineering",
    "MEMS": "Materials Engineering Science, Materials Science and Engineering",
    "MESC": "Materials Engineering Science",
    "MGT": "Management",
    "MHR": "Human Resource Management",
    "MICB": "Microbiology",
    "MINE": "Mining Engineering",
    "MJ": "Multimedia Journalism",
    "MKTG": "Marketing Management",
    "MN" : "Military Navy",
    "MNR": "Natural Resources",
    "MNSY": "Micro/Nano Systems",
    "MS": "Military Sciences (AROTC)",
    "MSE": "Materials Science and Engineering",
    "MTHE": "Mathematics Education",
    "MTRG": "Meteorology",
    "MUS": "Music",
    "NAD": "Nutrition and Dietetics",
    "NANO": "Nanoscience",
    "ND": "Nutrition and Dietetics",
    "NEUR": "Neuroscience",
    "NMED": "Nanomedicine",
    "NR": "Natural Resources",
    "NSEG": "Nuclear Science and Engineering",
    "NSFA": "National Security & Foreign Affairs",
    "NWCS": "Networking & Cybersecurity",
    "OCE": "Ocean Engineering",
    "OE": "Ocean Engineering",
    "PAPA": "Public Administration/Public Affairs",
    "PGG": "Planning, Governance, and Globalization",
    "PH": "Public Health",
    "PHIL": "Philosophy",
    "PHS": "Population Health Sciences",
    "PHTN": "Photonics",
    "PHYS": "Physics",
    "PIA": "Public and International Affairs",
    "PLSC": "Plant Science",
    "PM": "Property Management",
    "POLY": "Polymer Chemistry",
    "PPE": "Philosophy, Politics, and Economics",
    "PPWS": "Plant Pathology, Physiology and Weed Science",
    "PR": "Public Relations",
    "PSCI": "Political Science",
    "PSD": "Packaging Systems and Design",
    "PSVP": "Peace Studies",
    "PSYC": "Psychology",
    "PTW": "Professional and Technical Writing",
    "PUA": "Public and Urban Affairs",
    "RBMT": "Robotics and Mechatronics",
    "RDI": "Residential Development and Investment",
    "REAL": "Real Estate",
    "RED": "Residential Environments and Design",
    "RELC": "Real Estate for Commercial Properties",
    "RELR": "Real Estate for Residential Properties",
    "RESF": "Real Estate Finance",
    "RFMW": "Radio Frequency & Microwave",
    "RLCL": "Religion and Culture",
    "RPTM": "Reputation Management",
    "RTM": "Research in Translational Medicine",
    "RUS": "Russian",
    "RW": "Rhetoric and Writing",
    "SBIO": "Sustainable Biomaterials",
    "SC": "Secure Computing",
    "SFTW": "Software Systems",
    "SMA": "Sports Media and Analytics",
    "SOC": "Sociology",
    "SPAN": "Spanish",
    "SPCS": "Space Systems",
    "SPES": "Plant and Environmental Sciences",
    "SPIA": "School of Public and International Affairs",
    "SSC": "Smart and Sustainable Cities",
    "STAT": "Statistics",
    "STL": "Science, Technology, and Law",
    "STS": "Science and Technology Studies",
    "STU": "Studio Art",
    "SYSB": "Systems Biology",
    "SYSE": "Systems Engineering",
    "TA": "Theatre Arts",
    "TAC": "Cinema",
    "TBMH": "Translational Biology, Medicine and Health",
    "TCHE": "Technology Education",
    "TSC": "Technical and Scientific Communication",
    "UAP": "Urban and Environmental Policy and Planning",
    "UH" : "Honors College",
    "UNIV": "University Course Series",
    "URBA": "Urban Affairs",
    "URPL": "Urban and Regional Planning",
    "VM": "Veterinary Medicine",
    "WATR": "Water",
    "WCSP": "Wireless Communications and Signal Processing",
    "WGS": "Women's and Gender Studies",
    "WLC": "Wildlife Conservation",
    "WRPM": "Water: Resources, Policy, and Management"
}
